// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    id,
    actor_user_id,
    action,
    outcome,
    request_id,
    occurred_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditEventParams struct {
	ID          pgtype.UUID
	ActorUserID pgtype.UUID
	Action      string
	Outcome     string
	RequestID   string
	OccurredAt  pgtype.Timestamptz
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.Outcome,
		arg.RequestID,
		arg.OccurredAt,
	)
	return err
}

const getUserByEmployeeID = `-- name: GetUserByEmployeeID :one
SELECT id, employee_id, display_name, password_hash, role, active, created_at, updated_at
FROM users
WHERE employee_id = $1
`

func (q *Queries) GetUserByEmployeeID(ctx context.Context, employeeID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmployeeID, employeeID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, employee_id, display_name, password_hash, role, active, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
