// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package dbgen

import (
	"context"
)

// iteratorForInsertExecutionErrors implements pgx.CopyFromSource.
type iteratorForInsertExecutionErrors struct {
	rows                 []InsertExecutionErrorsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertExecutionErrors) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertExecutionErrors) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ExecutionID,
		r.rows[0].UseCaseID,
		r.rows[0].OccurredAt,
		r.rows[0].Code,
		r.rows[0].Label,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForInsertExecutionErrors) Err() error {
	return nil
}

func (q *Queries) InsertExecutionErrors(ctx context.Context, arg []InsertExecutionErrorsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"execution_errors"}, []string{"id", "execution_id", "use_case_id", "occurred_at", "code", "label", "created_at"}, &iteratorForInsertExecutionErrors{rows: arg})
}

// iteratorForInsertExecutions implements pgx.CopyFromSource.
type iteratorForInsertExecutions struct {
	rows                 []InsertExecutionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertExecutions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertExecutions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UseCaseID,
		r.rows[0].OccurredAt,
		r.rows[0].Outcome,
		r.rows[0].SourceRef,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForInsertExecutions) Err() error {
	return nil
}

func (q *Queries) InsertExecutions(ctx context.Context, arg []InsertExecutionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"executions"}, []string{"id", "use_case_id", "occurred_at", "outcome", "source_ref", "created_at"}, &iteratorForInsertExecutions{rows: arg})
}
