// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID          pgtype.UUID
	ActorUserID pgtype.UUID
	Action      string
	Outcome     string
	RequestID   string
	OccurredAt  pgtype.Timestamptz
}

type Execution struct {
	ID         pgtype.UUID
	UseCaseID  pgtype.UUID
	OccurredAt pgtype.Timestamptz
	Outcome    string
	SourceRef  string
	CreatedAt  pgtype.Timestamptz
}

type ExecutionError struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	UseCaseID   pgtype.UUID
	OccurredAt  pgtype.Timestamptz
	Code        string
	Label       string
	CreatedAt   pgtype.Timestamptz
}

type SyncRun struct {
	ID          pgtype.UUID
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	Status      string
	RowsRead    int32
	RowsWritten int32
	ErrorCode   pgtype.Text
}

type UseCase struct {
	ID        pgtype.UUID
	SourceKey string
	Name      string
	Status    string
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	EmployeeID   string
	DisplayName  string
	PasswordHash string
	Role         string
	Active       bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
