// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID          pgtype.UUID
	ActorUserID pgtype.UUID
	Action      string
	Outcome     string
	RequestID   string
	OccurredAt  pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	EmployeeID   string
	DisplayName  string
	PasswordHash string
	Role         string
	Active       bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
