// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AggregateSnapshot struct {
	ID                pgtype.UUID
	SyncRunID         pgtype.UUID
	SourceSnapshotKey string
	ImportedAt        pgtype.Timestamptz
	SourceRowCount    int32
}

type AuditEvent struct {
	ID          pgtype.UUID
	ActorUserID pgtype.UUID
	Action      string
	Outcome     string
	RequestID   string
	OccurredAt  pgtype.Timestamptz
}

type Execution struct {
	ID         pgtype.UUID
	UseCaseID  pgtype.UUID
	OccurredAt pgtype.Timestamptz
	Outcome    string
	SourceRef  string
	CreatedAt  pgtype.Timestamptz
}

type ExecutionError struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	UseCaseID   pgtype.UUID
	OccurredAt  pgtype.Timestamptz
	Code        string
	Label       string
	CreatedAt   pgtype.Timestamptz
}

type ProcessAggregateRow struct {
	ID                     pgtype.UUID
	AggregateSnapshotID    pgtype.UUID
	SyncRunID              pgtype.UUID
	UseCaseID              pgtype.UUID
	SourceProcessKey       string
	ProcessName            string
	PackageName            string
	EnvironmentName        pgtype.Text
	ExecutingCount         int32
	PendingCount           int32
	SuspendedCount         int32
	ResumedCount           int32
	SuccessfulCount        int32
	ErrorCount             int32
	StoppedCount           int32
	AverageDurationSeconds pgtype.Float8
	AveragePendingSeconds  pgtype.Float8
	SourceTotalRows        int32
	SourceEntityKey        string
	ImportedAt             pgtype.Timestamptz
}

type SyncRun struct {
	ID          pgtype.UUID
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	Status      string
	RowsRead    int32
	RowsWritten int32
	ErrorCode   pgtype.Text
}

type UseCase struct {
	ID        pgtype.UUID
	SourceKey string
	Name      string
	Status    string
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	EmployeeID   string
	DisplayName  string
	PasswordHash string
	Role         string
	Active       bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
