// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operational.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProcessAggregateRowsBySnapshot = `-- name: CountProcessAggregateRowsBySnapshot :one
SELECT count(id)
FROM process_aggregate_rows
WHERE aggregate_snapshot_id = $1
`

func (q *Queries) CountProcessAggregateRowsBySnapshot(ctx context.Context, aggregateSnapshotID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProcessAggregateRowsBySnapshot, aggregateSnapshotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishSyncRun = `-- name: FinishSyncRun :one
UPDATE sync_runs
SET
    finished_at = $2,
    status = $3,
    rows_read = $4,
    rows_written = $5,
    error_code = $6
WHERE id = $1
RETURNING id, started_at, finished_at, status, rows_read, rows_written, error_code
`

type FinishSyncRunParams struct {
	ID          pgtype.UUID
	FinishedAt  pgtype.Timestamptz
	Status      string
	RowsRead    int32
	RowsWritten int32
	ErrorCode   pgtype.Text
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, finishSyncRun,
		arg.ID,
		arg.FinishedAt,
		arg.Status,
		arg.RowsRead,
		arg.RowsWritten,
		arg.ErrorCode,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.RowsRead,
		&i.RowsWritten,
		&i.ErrorCode,
	)
	return i, err
}

const getAggregateSnapshotBySourceKey = `-- name: GetAggregateSnapshotBySourceKey :one
SELECT id, sync_run_id, source_snapshot_key, imported_at, source_row_count
FROM aggregate_snapshots
WHERE source_snapshot_key = $1
`

func (q *Queries) GetAggregateSnapshotBySourceKey(ctx context.Context, sourceSnapshotKey string) (AggregateSnapshot, error) {
	row := q.db.QueryRow(ctx, getAggregateSnapshotBySourceKey, sourceSnapshotKey)
	var i AggregateSnapshot
	err := row.Scan(
		&i.ID,
		&i.SyncRunID,
		&i.SourceSnapshotKey,
		&i.ImportedAt,
		&i.SourceRowCount,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, use_case_id, occurred_at, outcome, source_ref, created_at
FROM executions
WHERE id = $1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id pgtype.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.UseCaseID,
		&i.OccurredAt,
		&i.Outcome,
		&i.SourceRef,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionErrorByID = `-- name: GetExecutionErrorByID :one
SELECT id, execution_id, use_case_id, occurred_at, code, label, created_at
FROM execution_errors
WHERE id = $1
`

func (q *Queries) GetExecutionErrorByID(ctx context.Context, id pgtype.UUID) (ExecutionError, error) {
	row := q.db.QueryRow(ctx, getExecutionErrorByID, id)
	var i ExecutionError
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.UseCaseID,
		&i.OccurredAt,
		&i.Code,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getSyncRunByID = `-- name: GetSyncRunByID :one
SELECT id, started_at, finished_at, status, rows_read, rows_written, error_code
FROM sync_runs
WHERE id = $1
`

func (q *Queries) GetSyncRunByID(ctx context.Context, id pgtype.UUID) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getSyncRunByID, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.RowsRead,
		&i.RowsWritten,
		&i.ErrorCode,
	)
	return i, err
}

const getUseCaseBySourceKey = `-- name: GetUseCaseBySourceKey :one
SELECT id, source_key, name, status, updated_at
FROM use_cases
WHERE source_key = $1
`

func (q *Queries) GetUseCaseBySourceKey(ctx context.Context, sourceKey string) (UseCase, error) {
	row := q.db.QueryRow(ctx, getUseCaseBySourceKey, sourceKey)
	var i UseCase
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAggregateSnapshot = `-- name: InsertAggregateSnapshot :one
INSERT INTO aggregate_snapshots (
    id,
    sync_run_id,
    source_snapshot_key,
    imported_at,
    source_row_count
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_snapshot_key) DO NOTHING
RETURNING id, sync_run_id, source_snapshot_key, imported_at, source_row_count
`

type InsertAggregateSnapshotParams struct {
	ID                pgtype.UUID
	SyncRunID         pgtype.UUID
	SourceSnapshotKey string
	ImportedAt        pgtype.Timestamptz
	SourceRowCount    int32
}

func (q *Queries) InsertAggregateSnapshot(ctx context.Context, arg InsertAggregateSnapshotParams) (AggregateSnapshot, error) {
	row := q.db.QueryRow(ctx, insertAggregateSnapshot,
		arg.ID,
		arg.SyncRunID,
		arg.SourceSnapshotKey,
		arg.ImportedAt,
		arg.SourceRowCount,
	)
	var i AggregateSnapshot
	err := row.Scan(
		&i.ID,
		&i.SyncRunID,
		&i.SourceSnapshotKey,
		&i.ImportedAt,
		&i.SourceRowCount,
	)
	return i, err
}

type InsertExecutionErrorsParams struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	UseCaseID   pgtype.UUID
	OccurredAt  pgtype.Timestamptz
	Code        string
	Label       string
	CreatedAt   pgtype.Timestamptz
}

type InsertExecutionsParams struct {
	ID         pgtype.UUID
	UseCaseID  pgtype.UUID
	OccurredAt pgtype.Timestamptz
	Outcome    string
	SourceRef  string
	CreatedAt  pgtype.Timestamptz
}

type InsertProcessAggregateRowsParams struct {
	ID                     pgtype.UUID
	AggregateSnapshotID    pgtype.UUID
	SyncRunID              pgtype.UUID
	UseCaseID              pgtype.UUID
	SourceProcessKey       string
	ProcessName            string
	PackageName            string
	EnvironmentName        pgtype.Text
	ExecutingCount         int32
	PendingCount           int32
	SuspendedCount         int32
	ResumedCount           int32
	SuccessfulCount        int32
	ErrorCount             int32
	StoppedCount           int32
	AverageDurationSeconds pgtype.Float8
	AveragePendingSeconds  pgtype.Float8
	SourceTotalRows        int32
	SourceEntityKey        string
	ImportedAt             pgtype.Timestamptz
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO sync_runs (
    id,
    started_at,
    finished_at,
    status,
    rows_read,
    rows_written,
    error_code
) VALUES ($1, $2, NULL, 'running', 0, 0, NULL)
RETURNING id, started_at, finished_at, status, rows_read, rows_written, error_code
`

type StartSyncRunParams struct {
	ID        pgtype.UUID
	StartedAt pgtype.Timestamptz
}

func (q *Queries) StartSyncRun(ctx context.Context, arg StartSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, startSyncRun, arg.ID, arg.StartedAt)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.RowsRead,
		&i.RowsWritten,
		&i.ErrorCode,
	)
	return i, err
}

const upsertUseCase = `-- name: UpsertUseCase :one
INSERT INTO use_cases (
    id,
    source_key,
    name,
    status,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_key) DO UPDATE SET
    name = EXCLUDED.name,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
RETURNING id, source_key, name, status, updated_at
`

type UpsertUseCaseParams struct {
	ID        pgtype.UUID
	SourceKey string
	Name      string
	Status    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertUseCase(ctx context.Context, arg UpsertUseCaseParams) (UseCase, error) {
	row := q.db.QueryRow(ctx, upsertUseCase,
		arg.ID,
		arg.SourceKey,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
	)
	var i UseCase
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
