// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operational.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProcessAggregateRowsBySnapshot = `-- name: CountProcessAggregateRowsBySnapshot :one
SELECT count(id)
FROM process_aggregate_rows
WHERE aggregate_snapshot_id = $1
`

func (q *Queries) CountProcessAggregateRowsBySnapshot(ctx context.Context, aggregateSnapshotID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProcessAggregateRowsBySnapshot, aggregateSnapshotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishSyncRun = `-- name: FinishSyncRun :one
UPDATE sync_runs
SET
    finished_at = $2,
    status = $3,
    rows_read = $4,
    rows_written = $5,
    error_code = $6
WHERE id = $1
RETURNING id, started_at, finished_at, status, rows_read, rows_written, error_code
`

type FinishSyncRunParams struct {
	ID          pgtype.UUID
	FinishedAt  pgtype.Timestamptz
	Status      string
	RowsRead    int32
	RowsWritten int32
	ErrorCode   pgtype.Text
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, finishSyncRun,
		arg.ID,
		arg.FinishedAt,
		arg.Status,
		arg.RowsRead,
		arg.RowsWritten,
		arg.ErrorCode,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.RowsRead,
		&i.RowsWritten,
		&i.ErrorCode,
	)
	return i, err
}

const getAggregateSnapshotBySourceKey = `-- name: GetAggregateSnapshotBySourceKey :one
SELECT id, sync_run_id, source_snapshot_key, imported_at, source_row_count
FROM aggregate_snapshots
WHERE source_snapshot_key = $1
`

func (q *Queries) GetAggregateSnapshotBySourceKey(ctx context.Context, sourceSnapshotKey string) (AggregateSnapshot, error) {
	row := q.db.QueryRow(ctx, getAggregateSnapshotBySourceKey, sourceSnapshotKey)
	var i AggregateSnapshot
	err := row.Scan(
		&i.ID,
		&i.SyncRunID,
		&i.SourceSnapshotKey,
		&i.ImportedAt,
		&i.SourceRowCount,
	)
	return i, err
}

const getDashboardErrorGroups = `-- name: GetDashboardErrorGroups :many
SELECT
    code,
    label,
    count(id)::bigint AS error_count
FROM execution_errors
WHERE occurred_at >= $1
  AND occurred_at < $2
GROUP BY code, label
ORDER BY error_count DESC, code ASC, label ASC
`

type GetDashboardErrorGroupsParams struct {
	PeriodFrom pgtype.Timestamptz
	PeriodTo   pgtype.Timestamptz
}

type GetDashboardErrorGroupsRow struct {
	Code       string
	Label      string
	ErrorCount int64
}

func (q *Queries) GetDashboardErrorGroups(ctx context.Context, arg GetDashboardErrorGroupsParams) ([]GetDashboardErrorGroupsRow, error) {
	rows, err := q.db.Query(ctx, getDashboardErrorGroups, arg.PeriodFrom, arg.PeriodTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardErrorGroupsRow{}
	for rows.Next() {
		var i GetDashboardErrorGroupsRow
		if err := rows.Scan(&i.Code, &i.Label, &i.ErrorCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardExecutionTrend = `-- name: GetDashboardExecutionTrend :many
SELECT
    (
        date_trunc('month', occurred_at AT TIME ZONE 'UTC')
        AT TIME ZONE 'UTC'
    )::timestamptz AS bucket,
    count(id) FILTER (WHERE outcome = 'success')::bigint AS successful_count,
    count(id) FILTER (WHERE outcome = 'failure')::bigint AS failed_count
FROM executions
WHERE occurred_at >= $1
  AND occurred_at < $2
GROUP BY (
    date_trunc('month', occurred_at AT TIME ZONE 'UTC')
    AT TIME ZONE 'UTC'
)
ORDER BY bucket ASC
`

type GetDashboardExecutionTrendParams struct {
	PeriodFrom pgtype.Timestamptz
	PeriodTo   pgtype.Timestamptz
}

type GetDashboardExecutionTrendRow struct {
	Bucket          pgtype.Timestamptz
	SuccessfulCount int64
	FailedCount     int64
}

func (q *Queries) GetDashboardExecutionTrend(ctx context.Context, arg GetDashboardExecutionTrendParams) ([]GetDashboardExecutionTrendRow, error) {
	rows, err := q.db.Query(ctx, getDashboardExecutionTrend, arg.PeriodFrom, arg.PeriodTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardExecutionTrendRow{}
	for rows.Next() {
		var i GetDashboardExecutionTrendRow
		if err := rows.Scan(&i.Bucket, &i.SuccessfulCount, &i.FailedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardFreshness = `-- name: GetDashboardFreshness :one
SELECT
    (
        SELECT finished_at
        FROM sync_runs
        WHERE status = 'success'
          AND finished_at IS NOT NULL
        ORDER BY finished_at DESC, id DESC
        LIMIT 1
    ) AS last_successful_refresh_at,
    coalesce(
        (
            SELECT status
            FROM sync_runs
            ORDER BY started_at DESC, id DESC
            LIMIT 1
        ),
        ''
    )::text AS latest_status
`

type GetDashboardFreshnessRow struct {
	LastSuccessfulRefreshAt pgtype.Timestamptz
	LatestStatus            string
}

func (q *Queries) GetDashboardFreshness(ctx context.Context) (GetDashboardFreshnessRow, error) {
	row := q.db.QueryRow(ctx, getDashboardFreshness)
	var i GetDashboardFreshnessRow
	err := row.Scan(&i.LastSuccessfulRefreshAt, &i.LatestStatus)
	return i, err
}

const getDashboardSummaryAggregate = `-- name: GetDashboardSummaryAggregate :one
SELECT
    (SELECT count(use_cases.id) FROM use_cases)::bigint AS total_use_cases,
    (SELECT count(use_cases.id) FROM use_cases WHERE use_cases.status = 'active')::bigint AS active_use_cases,
    (
        SELECT count(volume_executions.id)
        FROM executions AS volume_executions
        WHERE volume_executions.occurred_at >= $1
          AND volume_executions.occurred_at < $2
    )::bigint AS execution_volume,
    (
        SELECT count(success_executions.id)
        FROM executions AS success_executions
        WHERE success_executions.occurred_at >= $1
          AND success_executions.occurred_at < $2
          AND success_executions.outcome = 'success'
    )::bigint AS successful_count,
    (
        SELECT count(failed_executions.id)
        FROM executions AS failed_executions
        WHERE failed_executions.occurred_at >= $1
          AND failed_executions.occurred_at < $2
          AND failed_executions.outcome = 'failure'
    )::bigint AS failed_executions
`

type GetDashboardSummaryAggregateParams struct {
	PeriodFrom pgtype.Timestamptz
	PeriodTo   pgtype.Timestamptz
}

type GetDashboardSummaryAggregateRow struct {
	TotalUseCases    int64
	ActiveUseCases   int64
	ExecutionVolume  int64
	SuccessfulCount  int64
	FailedExecutions int64
}

func (q *Queries) GetDashboardSummaryAggregate(ctx context.Context, arg GetDashboardSummaryAggregateParams) (GetDashboardSummaryAggregateRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummaryAggregate, arg.PeriodFrom, arg.PeriodTo)
	var i GetDashboardSummaryAggregateRow
	err := row.Scan(
		&i.TotalUseCases,
		&i.ActiveUseCases,
		&i.ExecutionVolume,
		&i.SuccessfulCount,
		&i.FailedExecutions,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, use_case_id, occurred_at, outcome, source_ref, created_at
FROM executions
WHERE id = $1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id pgtype.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.UseCaseID,
		&i.OccurredAt,
		&i.Outcome,
		&i.SourceRef,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionErrorByID = `-- name: GetExecutionErrorByID :one
SELECT id, execution_id, use_case_id, occurred_at, code, label, created_at
FROM execution_errors
WHERE id = $1
`

func (q *Queries) GetExecutionErrorByID(ctx context.Context, id pgtype.UUID) (ExecutionError, error) {
	row := q.db.QueryRow(ctx, getExecutionErrorByID, id)
	var i ExecutionError
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.UseCaseID,
		&i.OccurredAt,
		&i.Code,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSyncRun = `-- name: GetLatestSyncRun :one
SELECT id, started_at, finished_at, status, rows_read, rows_written, error_code
FROM sync_runs
ORDER BY started_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncRun(ctx context.Context) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getLatestSyncRun)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.RowsRead,
		&i.RowsWritten,
		&i.ErrorCode,
	)
	return i, err
}

const getSyncRunByID = `-- name: GetSyncRunByID :one
SELECT id, started_at, finished_at, status, rows_read, rows_written, error_code
FROM sync_runs
WHERE id = $1
`

func (q *Queries) GetSyncRunByID(ctx context.Context, id pgtype.UUID) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getSyncRunByID, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.RowsRead,
		&i.RowsWritten,
		&i.ErrorCode,
	)
	return i, err
}

const getUseCaseBySourceKey = `-- name: GetUseCaseBySourceKey :one
SELECT id, source_key, name, status, updated_at
FROM use_cases
WHERE source_key = $1
`

func (q *Queries) GetUseCaseBySourceKey(ctx context.Context, sourceKey string) (UseCase, error) {
	row := q.db.QueryRow(ctx, getUseCaseBySourceKey, sourceKey)
	var i UseCase
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getUseCaseSnapshotRows = `-- name: GetUseCaseSnapshotRows :many
WITH latest_successful_snapshot AS (
    SELECT aggregate_snapshots.id
    FROM aggregate_snapshots
    JOIN sync_runs ON sync_runs.id = aggregate_snapshots.sync_run_id
    WHERE sync_runs.status = 'success'
      AND sync_runs.finished_at IS NOT NULL
    ORDER BY sync_runs.finished_at DESC, sync_runs.id DESC, aggregate_snapshots.id DESC
    LIMIT 1
)
SELECT
    use_cases.id,
    use_cases.source_key,
    use_cases.name,
    use_cases.status,
    use_cases.updated_at,
    process_aggregate_rows.source_process_key,
    process_aggregate_rows.process_name,
    process_aggregate_rows.package_name,
    process_aggregate_rows.environment_name,
    process_aggregate_rows.executing_count,
    process_aggregate_rows.pending_count,
    process_aggregate_rows.suspended_count,
    process_aggregate_rows.resumed_count,
    process_aggregate_rows.successful_count,
    process_aggregate_rows.error_count,
    process_aggregate_rows.stopped_count
FROM use_cases
LEFT JOIN latest_successful_snapshot ON true
LEFT JOIN process_aggregate_rows
    ON process_aggregate_rows.aggregate_snapshot_id = latest_successful_snapshot.id
   AND process_aggregate_rows.use_case_id = use_cases.id
WHERE use_cases.id = $1
ORDER BY process_aggregate_rows.process_name ASC,
         process_aggregate_rows.source_process_key ASC
`

type GetUseCaseSnapshotRowsRow struct {
	ID               pgtype.UUID
	SourceKey        string
	Name             string
	Status           string
	UpdatedAt        pgtype.Timestamptz
	SourceProcessKey pgtype.Text
	ProcessName      pgtype.Text
	PackageName      pgtype.Text
	EnvironmentName  pgtype.Text
	ExecutingCount   pgtype.Int4
	PendingCount     pgtype.Int4
	SuspendedCount   pgtype.Int4
	ResumedCount     pgtype.Int4
	SuccessfulCount  pgtype.Int4
	ErrorCount       pgtype.Int4
	StoppedCount     pgtype.Int4
}

func (q *Queries) GetUseCaseSnapshotRows(ctx context.Context, useCaseID pgtype.UUID) ([]GetUseCaseSnapshotRowsRow, error) {
	rows, err := q.db.Query(ctx, getUseCaseSnapshotRows, useCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUseCaseSnapshotRowsRow{}
	for rows.Next() {
		var i GetUseCaseSnapshotRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.Name,
			&i.Status,
			&i.UpdatedAt,
			&i.SourceProcessKey,
			&i.ProcessName,
			&i.PackageName,
			&i.EnvironmentName,
			&i.ExecutingCount,
			&i.PendingCount,
			&i.SuspendedCount,
			&i.ResumedCount,
			&i.SuccessfulCount,
			&i.ErrorCount,
			&i.StoppedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAggregateSnapshot = `-- name: InsertAggregateSnapshot :one
INSERT INTO aggregate_snapshots (
    id,
    sync_run_id,
    source_snapshot_key,
    imported_at,
    source_row_count
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_snapshot_key) DO NOTHING
RETURNING id, sync_run_id, source_snapshot_key, imported_at, source_row_count
`

type InsertAggregateSnapshotParams struct {
	ID                pgtype.UUID
	SyncRunID         pgtype.UUID
	SourceSnapshotKey string
	ImportedAt        pgtype.Timestamptz
	SourceRowCount    int32
}

func (q *Queries) InsertAggregateSnapshot(ctx context.Context, arg InsertAggregateSnapshotParams) (AggregateSnapshot, error) {
	row := q.db.QueryRow(ctx, insertAggregateSnapshot,
		arg.ID,
		arg.SyncRunID,
		arg.SourceSnapshotKey,
		arg.ImportedAt,
		arg.SourceRowCount,
	)
	var i AggregateSnapshot
	err := row.Scan(
		&i.ID,
		&i.SyncRunID,
		&i.SourceSnapshotKey,
		&i.ImportedAt,
		&i.SourceRowCount,
	)
	return i, err
}

type InsertExecutionErrorsParams struct {
	ID          pgtype.UUID
	ExecutionID pgtype.UUID
	UseCaseID   pgtype.UUID
	OccurredAt  pgtype.Timestamptz
	Code        string
	Label       string
	CreatedAt   pgtype.Timestamptz
}

type InsertExecutionsParams struct {
	ID         pgtype.UUID
	UseCaseID  pgtype.UUID
	OccurredAt pgtype.Timestamptz
	Outcome    string
	SourceRef  string
	CreatedAt  pgtype.Timestamptz
}

type InsertProcessAggregateRowsParams struct {
	ID                     pgtype.UUID
	AggregateSnapshotID    pgtype.UUID
	SyncRunID              pgtype.UUID
	UseCaseID              pgtype.UUID
	SourceProcessKey       string
	ProcessName            string
	PackageName            string
	EnvironmentName        pgtype.Text
	ExecutingCount         int32
	PendingCount           int32
	SuspendedCount         int32
	ResumedCount           int32
	SuccessfulCount        int32
	ErrorCount             int32
	StoppedCount           int32
	AverageDurationSeconds pgtype.Float8
	AveragePendingSeconds  pgtype.Float8
	SourceTotalRows        int32
	SourceEntityKey        string
	ImportedAt             pgtype.Timestamptz
}

const listUseCaseSnapshotRows = `-- name: ListUseCaseSnapshotRows :many
WITH latest_successful_snapshot AS (
    SELECT aggregate_snapshots.id
    FROM aggregate_snapshots
    JOIN sync_runs ON sync_runs.id = aggregate_snapshots.sync_run_id
    WHERE sync_runs.status = 'success'
      AND sync_runs.finished_at IS NOT NULL
    ORDER BY sync_runs.finished_at DESC, sync_runs.id DESC, aggregate_snapshots.id DESC
    LIMIT 1
)
SELECT
    use_cases.id,
    use_cases.source_key,
    use_cases.name,
    use_cases.status,
    use_cases.updated_at,
    process_aggregate_rows.source_process_key,
    process_aggregate_rows.process_name,
    process_aggregate_rows.package_name,
    process_aggregate_rows.environment_name,
    process_aggregate_rows.executing_count,
    process_aggregate_rows.pending_count,
    process_aggregate_rows.suspended_count,
    process_aggregate_rows.resumed_count,
    process_aggregate_rows.successful_count,
    process_aggregate_rows.error_count,
    process_aggregate_rows.stopped_count
FROM use_cases
LEFT JOIN latest_successful_snapshot ON true
LEFT JOIN process_aggregate_rows
    ON process_aggregate_rows.aggregate_snapshot_id = latest_successful_snapshot.id
   AND process_aggregate_rows.use_case_id = use_cases.id
WHERE ($1::text = ''
       OR strpos(lower(use_cases.name), lower($1::text)) > 0)
  AND ($2::text = ''
       OR use_cases.status = $2::text)
ORDER BY use_cases.name ASC, use_cases.id ASC,
         process_aggregate_rows.process_name ASC,
         process_aggregate_rows.source_process_key ASC
`

type ListUseCaseSnapshotRowsParams struct {
	SearchQuery  string
	StatusFilter string
}

type ListUseCaseSnapshotRowsRow struct {
	ID               pgtype.UUID
	SourceKey        string
	Name             string
	Status           string
	UpdatedAt        pgtype.Timestamptz
	SourceProcessKey pgtype.Text
	ProcessName      pgtype.Text
	PackageName      pgtype.Text
	EnvironmentName  pgtype.Text
	ExecutingCount   pgtype.Int4
	PendingCount     pgtype.Int4
	SuspendedCount   pgtype.Int4
	ResumedCount     pgtype.Int4
	SuccessfulCount  pgtype.Int4
	ErrorCount       pgtype.Int4
	StoppedCount     pgtype.Int4
}

func (q *Queries) ListUseCaseSnapshotRows(ctx context.Context, arg ListUseCaseSnapshotRowsParams) ([]ListUseCaseSnapshotRowsRow, error) {
	rows, err := q.db.Query(ctx, listUseCaseSnapshotRows, arg.SearchQuery, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUseCaseSnapshotRowsRow{}
	for rows.Next() {
		var i ListUseCaseSnapshotRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.Name,
			&i.Status,
			&i.UpdatedAt,
			&i.SourceProcessKey,
			&i.ProcessName,
			&i.PackageName,
			&i.EnvironmentName,
			&i.ExecutingCount,
			&i.PendingCount,
			&i.SuspendedCount,
			&i.ResumedCount,
			&i.SuccessfulCount,
			&i.ErrorCount,
			&i.StoppedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO sync_runs (
    id,
    started_at,
    finished_at,
    status,
    rows_read,
    rows_written,
    error_code
) VALUES ($1, $2, NULL, 'running', 0, 0, NULL)
RETURNING id, started_at, finished_at, status, rows_read, rows_written, error_code
`

type StartSyncRunParams struct {
	ID        pgtype.UUID
	StartedAt pgtype.Timestamptz
}

func (q *Queries) StartSyncRun(ctx context.Context, arg StartSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, startSyncRun, arg.ID, arg.StartedAt)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.RowsRead,
		&i.RowsWritten,
		&i.ErrorCode,
	)
	return i, err
}

const upsertUseCase = `-- name: UpsertUseCase :one
INSERT INTO use_cases (
    id,
    source_key,
    name,
    status,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_key) DO UPDATE SET
    name = EXCLUDED.name,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
RETURNING id, source_key, name, status, updated_at
`

type UpsertUseCaseParams struct {
	ID        pgtype.UUID
	SourceKey string
	Name      string
	Status    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertUseCase(ctx context.Context, arg UpsertUseCaseParams) (UseCase, error) {
	row := q.db.QueryRow(ctx, upsertUseCase,
		arg.ID,
		arg.SourceKey,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
	)
	var i UseCase
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
