// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) (SyncRun, error)
	GetExecutionByID(ctx context.Context, id pgtype.UUID) (Execution, error)
	GetExecutionErrorByID(ctx context.Context, id pgtype.UUID) (ExecutionError, error)
	GetSyncRunByID(ctx context.Context, id pgtype.UUID) (SyncRun, error)
	GetUseCaseBySourceKey(ctx context.Context, sourceKey string) (UseCase, error)
	GetUserByEmployeeID(ctx context.Context, employeeID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertExecutionErrors(ctx context.Context, arg []InsertExecutionErrorsParams) (int64, error)
	InsertExecutions(ctx context.Context, arg []InsertExecutionsParams) (int64, error)
	StartSyncRun(ctx context.Context, arg StartSyncRunParams) (SyncRun, error)
	UpsertUseCase(ctx context.Context, arg UpsertUseCaseParams) (UseCase, error)
}

var _ Querier = (*Queries)(nil)
