// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	GetUserByEmployeeID(ctx context.Context, employeeID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
